clear;
echo "----------------------------------------------------------------";
echo "----------------------------Hello-------------------------------";
echo "----------------------------------------------------------------";
#./new.sh;
cd ~/apps/apache-tomcat-7.0.39/bin;
./shutdown.sh;
cd ../webapps/;
rm -r SpringMVC;
rm SpringMVC.war;
cd ~/workspace/EasyOil;
#mvn clean;
mvn package;
cd target;
cp SpringMVC.war ~/apps/apache-tomcat-7.0.39/webapps/;
cd ~/apps/apache-tomcat-7.0.39/bin;
./startup.sh;
echo "----------------------------------------------------------------";
echo "---------------------------Done---------------------------------";
echo "----------------------------------------------------------------";
